// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Chirp struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	ExpiresAt time.Time
	RevokedAt interface{}
}

type User struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}
